import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextArea;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.Background;
import javafx.scene.layout.BorderPane;
import javafx.scene.text.Font;
import javafx.scene.text.FontPosture;

public class CreditsScene extends Scene {
    private BorderPane root;
    private TextArea creditsTextArea;
    private Button backButton;
    private BackListener backListener;

    public CreditsScene() {
        super(new BorderPane());
        root = (BorderPane) getRoot();

        // INIT
        creditsTextArea = new TextArea();
        creditsTextArea.setEditable(false);
        creditsTextArea.setText(creditsText());
        backButton = new Button();

        // CLOSEBUTTON

        backButton = new Button();
        ImageView backImage = new ImageView(new Image("assets/ui/back.png"));
        backButton.setGraphic(backImage);
        backButton.setPrefHeight(50);
        backButton.setBackground(Background.EMPTY);
        backImage.setPreserveRatio(true);
        backImage.setFitHeight(50);

        backButton.setOnAction(e->{
            backListener.goBack();
        });

        // LAYOUT

        root.setCenter(creditsTextArea);
        root.setBottom(backButton);
    }

    public void setBackListener(BackListener backListener) {
        this.backListener = backListener;
    }

    public String creditsText() {
        StringBuilder sb = new StringBuilder();

        sb.append("Icons: game-icons.txt\n");
        sb.append("Forest background: Image by upklyak on Freepik\n");
        sb.append("Shop background: Image by upklyak on Freepik\n");
        sb.append("Knight: Image by rawpixel.com on Freepik\n");
        sb.append("Fox, Vampir, Crazy Muppet, Christmas Zombie: Generated by AI on craiyon\n");

        return sb.toString();
    }
}
